# Generated by Django 3.0.5 on 2022-12-11 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import ecom_api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_url', models.TextField(unique=True)),
                ('type', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('dis_price', models.FloatField()),
                ('color', models.CharField(max_length=255)),
                ('size', djongo.models.fields.ArrayField(model_container=ecom_api.models.Sizes, model_form_class=ecom_api.models.SizesForm)),
                ('images', djongo.models.fields.ArrayField(model_container=ecom_api.models.Images, model_form_class=ecom_api.models.ImagesForm)),
                ('desc', djongo.models.fields.JSONField(blank=True, null=True)),
                ('desc_add', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeProductUrl',
            fields=[
                ('product_url_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_url', models.TextField(unique=True)),
                ('product_type', models.CharField(max_length=255)),
                ('is_scraped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_api.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
