# Generated by Django 3.0.5 on 2022-12-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product_id',
        ),
    ]
