# Generated by Django 3.0.5 on 2022-12-12 05:45

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_api', '0002_auto_20221212_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='ecom_api.Product'),
        ),
    ]
